### ISSUE TITLE
manual - weather description

### ISSUE THREAD

**Issue by kemanian** [PSUmodeling/Cycles#27]
Yuning the manual description of weather.day seems to be off. The headers should be
year
doy
pp
...

**Comment by shiyuning** [comment]
@kemanian Are you referring to the online manual? I checked the description of weather file and the header seems OK: [https://psumodeling.github.io/Cycles/#weather-file-weather](https://psumodeling.github.io/Cycles/#weather-file-weather). Let me know where you saw the error.
