### ISSUE TITLE
Spin-up in multi-mode

### ISSUE THREAD

**Issue by rkrozum** [PSUmodeling/Cycles#29]
The multi-mode is great for running many simulations and keeping track of them in one file. Could a spin-up mode option be added to this file?

**Comment by shiyuning** [comment]
Does the -s parameter work with multi-mode?
Or do you mean running some simulations with spin-up, and some without?

**Comment by rkrozum** [comment]
Some with, some without
________________________________

**Comment by shiyuning** [comment]
At this point, I would suggest using two multi-mode control files, one for spin-up and one for normal simulation. I am cleaning/debugging Cycles code right now. I will talk with @kemanian regarding input format soon. At that point, we will see if it makes sense to add `spinup` as an input parameter in the control file.
