### ISSUE TITLE
Multi-mode log file

### ISSUE THREAD

**Issue by rkrozum** [PSUmodeling/Cycles#32]
For errors in multimode files with a large number of simulations, it would be helpful if errors were saved to a log file (e.g. missing input file), and then Cycles jumps to the next simulation.

**Comment by shiyuning** [comment]
@rkrozum If we run the model in multi-mode, any error would cause the whole program to stop. We cannot stop the current  "project" and jump to the next simulation.

I would suggest using a script to run batch jobs instead of the "multi-mode". That gives you more flexibility.
